### ISSUE TITLE
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

### ISSUE THREAD

**Issue by JakeHenshall** [iGitScor/critical-webpack-plugin#17]
Hi,

**Do you want to request a *feature* or report a *bug*?**

_Report a bug_

**What is the current behaviour?**

I will not compile.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Installed using Yarn and followed the GitHub installation. I'm trying to read from .twig files, I'm using WordPress and Enqueuing the styles and scripts.

```
 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/jake/code/website/public/content/themes/website/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at module.exports (/Users/jake/code/website/public/content/themes/website/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/Users/jake/code/website/public/content/themes/website/node_modules/svgo/lib/svgo.js:21:19)
    at Object.<anonymous> (/Users/jake/code/website/public/content/themes/website/node_modules/postcss-image-inliner/lib/image.js:5:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jake/code/website/public/content/themes/website/node_modules/postcss-image-inliner/index.js:11:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jake/code/website/public/content/themes/website/node_modules/critical/lib/core.js:13:20)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
```

**What is the expected behaviour?**

create a critical.css file.

Please let me know if there is anything else that I need to provide.

Thank you!

**Comment by iGitScor** [comment]
Hi,

Thank you for reaching us @JakeHenshall ! 👍 
We will investigate to correct your issue.

I need more information about your configuration.
Can you transmit version for node, npm, yarn, this plugin and webpack.

Sorry for the response delay 😞

**Comment by iGitScor** [comment]
Hi @JakeHenshall,

Any update, please 😄 

Thank you !

**Comment by JakeHenshall** [comment]
@iGitScor  Sure, I'll provide it as soon as I can.

**Comment by AnuragKDwivedi** [comment]
@iGitScor @JakeHenshall I am also having same issue.

fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'H:\Anurag\USA project\updated\SnapParc\config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.readFileSync (H:\Anurag\USA project\updated\SnapParc\node_modules\aws-sdk\lib\util.js:97:26)
    at Config.loadFromPath (H:\Anurag\USA project\updated\SnapParc\node_modules\aws-sdk\lib\config.js:402:39)
    at Object.<anonymous> (H:\Anurag\USA project\updated\SnapParc\Routes\profilePictureRoutes.js:9:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (H:\Anurag\USA project\updated\SnapParc\server.js:48:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3

**Comment by iGitScor** [comment]
Hi @AnuragKDwivedi,

Same answer, I need more information
Can you give me your version for node, npm, yarn, this plugin and webpack, please ?

Thank you

**Comment by Niharika-rama** [comment]
@iGitScor  i'm having the same issue using webpack 4.3.0 , node 8.9.4, npm 5.6.0

**Comment by iGitScor** [comment]
All right, I'll keep you in touch

**Comment by EmilMoe** [comment]
Make sure you don't do versioning

```
// run versioning on production only
if (mix.inProduction()) {
    mix.version();
}
```

**This was probably not related to Laravel Mix, so keep in mind you might have to change syntax !**

**Comment by amirhosseinnazari** [comment]
Same problem here with 
node version 8.10.0  
npm 3.5.2 
`return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
`

**Comment by annder** [comment]
Well, I also met a situation like yours.

I fixed method for instance.

```diff
  // error codes
 function export_file(name) {
-   return fs.readFileSync(__dirname + name,"utf");
 }
```

But  correct code is:

```diff
  // error codes
 function export_file(name) {
+   return fs.readFileSync(name,"utf");
 }
```


Maybe sure for you.
